export const cars = [
  {
    id: 2,
    carTypeId: 3,
    name: "Izzi's Car",
    ownerId: 3,
    state: 'LOCKED',
    fuelType: 'petrol',
    horsepower: 125,
    licensePlate: 'FOO-BAR 42',
    info: 'Please no scratches!',
  },
  {
    id: 4,
    carTypeId: 1,
    name: 'Test',
    ownerId: 1,
    state: 'LOCKED',
    fuelType: 'diesel',
    horsepower: 230,
    licensePlate: 'RAB 239 D',
    info: 'Ev Car',
  },
  {
    id: 1,
    carTypeId: 1,
    name: "Bea's Car",
    ownerId: 1,
    state: 'LOCKED',
    fuelType: 'electric',
    horsepower: 250,
    licensePlate: null,
    info: null,
  },
]
